spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/weekly_plan
    driver-class-name: org.mariadb.jdbc.Driver
    username: planner
    password: planner
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
